In [3]:
# Create a NumPy array of numbers from 1 to 10.
import numpy as np
Array1 = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array From 1 to 10: ")
print(Array1)

Array From 1 to 10: 
[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# Create a 3×3 array of zeros.
import numpy as np
print("[3x3] Array of Zeros:  \n", np.zeros((3,3)))

[3x3] Array of Zeros:  
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# Create a 4×4 array filled with the number 7
import numpy as np
Array1 = np.ones((4,4))
Array2 = Array1*7
print("[4x4] array with Sevens: \n",Array2)

[4x4] array with Sevens: 
 [[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [24]:
# Create an array of even numbers between 10 and 30
import numpy as np
Array1 = np.arange(10,30,2)
print("Even numbers between 10 and 30: \n", Array1)

Even numbers between 10 and 30: 
 [10 12 14 16 18 20 22 24 26 28]


In [28]:
# Create a 5×5 identity matrix
import numpy as np
Array1 = np.eye(5,5)
print(" 5x5 Identity Matrix:\n",Array1)

 5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
# Find the shape, size, and data type of this array: arr = np.array([[1,2,3],[4,5,6]])
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Shape of Array: \n" ,arr.shape)
print("Size of Array: \n" ,arr.size)
print("Datatype of Array: \n" ,arr.dtype)

Shape of Array: 
 (2, 3)
Size of Array: 
 6
Datatype of Array: 
 int64


In [36]:
# Reshape a 1D array of numbers from 1–12 into a 3×4 matrix
import numpy as np
Array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Array Before Reshape:\n",Array1)
Array2 = Array1.reshape(3,4)
print("Array After Reshape into 3x4: \n",Array2)

Array Before Reshape:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Array After Reshape into 3x4: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
# Extract all elements greater than 50 from this array: arr = np.array([10, 60, 45, 80, 30, 90])
import numpy as np
arr = np.array([10, 60, 45, 80, 30, 90])
Array1 = arr[arr>50]
print(arr)
print("Elements greater than 50: \n",Array1)

[10 60 45 80 30 90]
Elements greater than 50: 
 [60 80 90]


In [51]:
# Find the mean, median, and standard deviation of: arr = np.array([5, 10, 15, 20, 25])
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(arr)
print("Mean of Array is: ",np.mean(arr))
print("Median of Array is:",np.median(arr))
print("Standard Deviation of Array is:",np.std(arr))

[ 5 10 15 20 25]
Mean of Array is:  15.0
Median of Array is: 15.0
Standard Deviation of Array is: 7.0710678118654755


In [55]:
# Add two arrays element-wise: a = np.array([1,2,3]) and b = np.array([4,5,6])
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Sum of",a,"and",b,"is: ",np.add(a, b))

Sum of [1 2 3] and [4 5 6] is:  [5 7 9]


In [68]:
# Find the maximum and minimum value in a 3×3 random array.
import numpy as np
arr = np.random.rand(3,3)
print(arr)
print("Maximum Numberis: ",np.max(arr))
print("Minimum Number is: ",np.min(arr))


[[0.37689629 0.22119999 0.64810585]
 [0.95386828 0.13664967 0.47898657]
 [0.93992433 0.1277133  0.47526849]]
Maximum Numberis:  0.9538682787535078
Minimum Number is:  0.127713301959007


In [70]:
# Sort this array: arr = np.array([12, 4, 7, 1, 9])
import numpy as np
arr = np.array([12, 4, 7, 1, 9])
print("Array Befor Sorting: ",arr)
print("Array After Sorting: ",np.sort(arr))

Array Befor Sorting:  [12  4  7  1  9]
Array After Sorting:  [ 1  4  7  9 12]


In [75]:
# Replace all negative numbers in this array with 0: arr = np.array([3, -1, 5, -7, 8])
import numpy as np
arr = np.array([3, -1, 5, -7, 8])
arr[arr < 0] = 0
print(arr)

[3 0 5 0 8]
